version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cmpc_books
    volumes:
      - pgdata:/var/lib/postgresql/data
  nest-app:
    image: node:20
    container_name: nest-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4000:4000'
    command: sh -c "npm install && npm run start:dev"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=cmpc_books
    depends_on:
      - postgres
volumes:
  pgdata:
